name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"

          git clone https://AhmedRagabSaad:$HF_TOKEN@huggingface.co/spaces/AhmedRagabSaad/SalesVision-AI-Demo space

          rsync -av \
            --exclude '.git' \
            --exclude 'space' \
            --exclude '__pycache__' \
            --exclude '*.pyc' \
            --exclude '.coverage' \
            --exclude '*.csv' \
            --exclude '.github' \
            ./ space/

          cd space

          git add .

          git commit -m "Auto deploy from GitHub" || echo "No changes to commit"

          git push